export const TRANSCRIBE = 'transribe'
export const SPEAK = 'speak'
export const START_SERVER = 'server:start'
export const CHAT = 'ai:chat'
export const CHAT_STREAM = 'ai:chatStream'
export const CHAT_CHUNK = 'ai:chaChunk'
