import { homedir } from 'os'
import { join } from 'path'
import { writeFileSync, mkdirSync } from 'fs'

// Written to ~/.echo/chrome-debug.sh on startup. Scout runs it to bring up a
// browser with a remote-debugging port for the chrome-devtools MCP. It probes
// for whatever Chromium-family browser is actually installed (native binary or
// flatpak) instead of assuming a specific Google Chrome install — so the
// browser feature works on any Linux box, not just the dev machine.
const LAUNCHER = `#!/usr/bin/env bash
# Auto-generated by Echo — do not edit; it's rewritten on every launch.
# Brings up an installed Chromium-family browser with remote debugging on a
# dedicated profile, then blocks until the port is reachable. Idempotent.
PORT=9222
PROFILE="$HOME/.echo/browser-cdp-profile"

if curl -s "http://127.0.0.1:$PORT/json/version" >/dev/null 2>&1; then
  echo "browser debug port already up"
  exit 0
fi

launch=""
for bin in google-chrome-stable google-chrome chromium chromium-browser \\
           brave-browser microsoft-edge-stable microsoft-edge; do
  if command -v "$bin" >/dev/null 2>&1; then launch="$bin"; break; fi
done

if [ -z "$launch" ] && command -v flatpak >/dev/null 2>&1; then
  for app in com.google.Chrome org.chromium.Chromium com.brave.Browser com.microsoft.Edge; do
    if flatpak info "$app" >/dev/null 2>&1; then launch="flatpak run $app"; break; fi
  done
fi

if [ -z "$launch" ]; then
  echo "NO_BROWSER: no Chromium-family browser found (install google-chrome, chromium, or brave)" >&2
  exit 2
fi

echo "launching: $launch"
setsid $launch \\
  --remote-debugging-port="$PORT" \\
  --user-data-dir="$PROFILE" \\
  --no-first-run --no-default-browser-check \\
  >/dev/null 2>&1 &

for i in $(seq 1 30); do
  if curl -s "http://127.0.0.1:$PORT/json/version" >/dev/null 2>&1; then
    echo "browser debug port ready after $i seconds"
    exit 0
  fi
  sleep 1
done

echo "TIMEOUT: browser did not expose debug port on $PORT" >&2
exit 1
`

export function ensureBrowserLauncher(): void {
  try {
    const dir = join(homedir(), '.echo')
    mkdirSync(dir, { recursive: true })
    writeFileSync(join(dir, 'chrome-debug.sh'), LAUNCHER, { mode: 0o755 })
  } catch (err) {
    console.error('[browser] failed to write launcher script:', err)
  }
}
